# Generated by Django 4.2.20 on 2025-04-23 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_tag_tag_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tag',
            new_name='tags',
        ),
    ]
